# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'File_transfer_system.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(600, 400)
        self.title = QtWidgets.QLabel(mainWindow)
        self.title.setGeometry(QtCore.QRect(190, 20, 200, 60))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.transmit_pushButton = QtWidgets.QPushButton(mainWindow)
        self.transmit_pushButton.setGeometry(QtCore.QRect(240, 290, 100, 40))
        self.transmit_pushButton.setObjectName("transmit_pushButton")
        self.layoutWidget = QtWidgets.QWidget(mainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 80, 281, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(13, 0, 13, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uname_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.uname_lineEdit.setObjectName("uname_lineEdit")
        self.verticalLayout.addWidget(self.uname_lineEdit)
        self.host_ip_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.host_ip_lineEdit.setObjectName("host_ip_lineEdit")
        self.verticalLayout.addWidget(self.host_ip_lineEdit)
        self.password_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout.addWidget(self.password_lineEdit)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "File transfer system"))
        self.title.setText(_translate("mainWindow", "File transfer system"))
        self.transmit_pushButton.setText(_translate("mainWindow", "发送"))
        self.uname_lineEdit.setPlaceholderText(_translate("mainWindow", "Please enter the uname"))
        self.host_ip_lineEdit.setPlaceholderText(_translate("mainWindow", "Please enter the host address"))
        self.password_lineEdit.setPlaceholderText(_translate("mainWindow", "Please enter the password"))
