# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_transfer_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 0, 67, 22))
        self.comboBox.setObjectName("comboBox")
        self.fontComboBox = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox.setGeometry(QtCore.QRect(80, 0, 211, 22))
        self.fontComboBox.setObjectName("fontComboBox")
        self.groupBox_local = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_local.setGeometry(QtCore.QRect(0, 50, 311, 371))
        self.groupBox_local.setObjectName("groupBox_local")
        self.listWidget_local = QtWidgets.QListWidget(self.groupBox_local)
        self.listWidget_local.setGeometry(QtCore.QRect(10, 71, 291, 291))
        self.listWidget_local.setObjectName("listWidget_local")
        self.groupBox_remote = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_remote.setGeometry(QtCore.QRect(330, 50, 311, 371))
        self.groupBox_remote.setObjectName("groupBox_remote")
        self.listWidget_remote = QtWidgets.QListWidget(self.groupBox_remote)
        self.listWidget_remote.setGeometry(QtCore.QRect(10, 70, 291, 291))
        self.listWidget_remote.setObjectName("listWidget_remote")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_local.setTitle(_translate("MainWindow", "本地文件"))
        self.groupBox_remote.setTitle(_translate("MainWindow", "远程文件"))
